### ISSUE TITLE
Setup : EntityProxy::$tag does not exist 

### ISSUE THREAD

**Issue by AlucardleVash** [Victoire/victoire#988] opened 2017-09-08 15:12 UTC
## Description
On setup phase : 
bin/console -e=dev doctrine:schema:create

[ReflectionException]                                                        
  Property Victoire\Bundle\CoreBundle\Entity\EntityProxy::$tag does not exist 

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |  | Page           |  |
| Blog           |          | Query          |          |
| BusinessEntity |          |Seo             |          |
| BusinessPage   |          | Sitemap        |          |
| Core           |       &#10004;   | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |
| UI             |          |                |          |

**Comment by AlucardleVash** [comment] 2017-09-08 15:14
related to ? 
https://github.com/Victoire/victoire/pull/961

**Comment by AlucardleVash** [comment] 2017-09-08 15:19
With "symfony/symfony": "3.2.9" in composer, everything seem's work

**Comment by Yoann-TYT** [comment] 2017-09-14 14:15
Yep, this problem seems to be not solved. Related to #951 ;)

**Comment by alexislefebvre** [comment] 2017-12-28 10:49
Closing this since it's a duplicate of #951.

**Closed by alexislefebvre** 2017-12-28 10:49 UTC
