### ISSUE TITLE
Blog rss shows the draft articles

### ISSUE THREAD

**Issue by BFoucher** [Victoire/victoire#923] opened 2017-05-19 15:27 UTC
## Description
Rss feed shows all articles even those unpublished

## Resolution Ideas
filter request?

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |  | Page           |   |
| Blog           |   &#10004;       | Query          |          |
| BusinessEntity |          |Seo             |          |
| BusinessPage   |          | Sitemap        |          |
| Core           |          | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |

**Comment by alexislefebvre** [comment] 2017-11-28 14:13
The problem is still here.

Here is the RSS feed: https://troopers.agency/fr/victoire-dcms/blog/feed/15.rss

It contains a link to this draft article: https://troopers.agency/fr/blog/cd-act-4-deploiement-automatique-grace-a-rancher-et-gitlabci

**Comment by alexislefebvre** [comment] 2018-06-14 12:19
Fixed by #1076

**Closed by alexislefebvre** 2018-06-14 12:19 UTC
Labels: Type : Bug, in progress
