### ISSUE TITLE
Compatibility with symfony 3.2.10

### ISSUE THREAD

**Issue by lenybernard** [Victoire/victoire#951] opened 2017-07-05 08:15 UTC
## Description
The version 3.2.10 of `symfony/symfony` makes victoire crash. 

## Temporary resolution
Fix the `"symfony/symfony": "3.2.9"` version in you project's composer.json

## Resolution Ideas
I don't know yet what between [v3.2.9...v3.2.10 ](https://github.com/symfony/symfony/compare/v3.2.9...v3.2.10) fucked victoire. 👀

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |  | Page           |  |
| Blog           |          | Query          |          |
| BusinessEntity |          |Seo             |          |
| BusinessPage   |          | Sitemap        |          |
| Core           |  &#10004; | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |
| UI             |          |                |          |

**Comment by alexislefebvre** [comment] 2017-07-05 08:23
Related to #948 and #950.

**Comment by Yoann-TYT** [comment] 2017-07-07 16:12
I checked a bit the problem, and I think it's caused by the symfony issue #23086.
In Victoire\Bundle\BusinessEntityBundle\Annotation\AnnotationDriver
Line 94, you use the function get_declared_classes(), but from 3.2.10, you don't get all classes ( because of performance ca:wa I think ),
in particular, you haven't got BlogBundle\Entity\Article... And this cause the trouble.

Issue #28086 of Symfony is merged with all branches, so we have to find a solution :)

Hope it can help you

**Comment by Yoann-TYT** [comment] 2017-07-11 09:30
After a few tests, the problem seems coming from issue #23014 of Symfony ( merged in 3.2.10 ).
I don't know why...
Hope it can help you

**Comment by alexislefebvre** [comment] 2017-07-30 20:57
Thanks to Travis CI, we'll be able to test several versions of Symfony in the same time. For the moment, only Symfony 3.2.9 works with a limited subset of Behat features, while Symfony 2.8, 3.2.10 and 3.3 crash when preparing tests: https://travis-ci.org/alexislefebvre/victoire/builds/259172872

**Comment by alexislefebvre** [comment] 2017-12-28 11:20
Here is the full error stack with Symfony 3.2.11:

```
$ php Tests/App/bin/console --env=test doctrine:schema:update -vvv
[2017-12-28 12:17:34] event.DEBUG: Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure". {"event":"console.command","listener":"Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::configure"} 
[2017-12-28 12:17:34] event.DEBUG: Notified event "console.command" to listener "Symfony\Bridge\Monolog\Handler\ConsoleHandler::onCommand". {"event":"console.command","listener":"Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler::onCommand"} 
[2017-12-28 12:17:35] event.DEBUG: Notified event "console.exception" to listener "Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onException". {"event":"console.exception","listener":"Symfony\\Bundle\\SwiftmailerBundle\\EventListener\\EmailSenderListener::onException"} 

                                                                                   
  [ReflectionException]                                                            
  Property Victoire\Bundle\CoreBundle\Entity\EntityProxy::$article does not exist  
                                                                                   

Exception trace:
 () at vendors/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:80
 ReflectionProperty->__construct() at vendors/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:80
 Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getAccessibleProperty() at vendors/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php:971
 Doctrine\ORM\Mapping\ClassMetadataInfo->wakeupReflection() at vendors/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:747
 Doctrine\ORM\Mapping\ClassMetadataFactory->wakeupReflection() at vendors/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:344
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata() at vendors/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:78
 Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata() at vendors/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:217
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() at vendors/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:115
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getAllMetadata() at vendors/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php:62
 Doctrine\ORM\Tools\Console\Command\SchemaTool\AbstractCommand->execute() at vendors/doctrine/doctrine-bundle/Command/Proxy/UpdateSchemaDoctrineCommand.php:50
 Doctrine\Bundle\DoctrineBundle\Command\Proxy\UpdateSchemaDoctrineCommand->execute() at vendors/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at vendors/symfony/symfony/src/Symfony/Component/Console/Application.php:854
 Symfony\Component\Console\Application->doRunCommand() at vendors/symfony/symfony/src/Symfony/Component/Console/Application.php:201
 Symfony\Component\Console\Application->doRun() at vendors/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:81
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendors/symfony/symfony/src/Symfony/Component/Console/Application.php:125
 Symfony\Component\Console\Application->run() at /home/alexis/Works/victoire/victoire/Tests/App/bin/console:30

doctrine:schema:update [--complete] [--dump-sql] [-f|--force] [--em [EM]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by alexislefebvre** [comment] 2017-12-28 15:31
Maybe we should use a proxy manager like https://github.com/Ocramius/ProxyManager instead of using a custom `EntityProxy`. It is used by Symfony since 2 years: https://github.com/symfony/symfony/blob/51a71ab74ac4538905c782d1ba5baf89be51e85e/composer.json#L79

**Closed** 2018-01-10 08:17 UTC
Labels: Priority : High, Type : Bug, Type : Technical debt, in progress
